### ISSUE TITLE
Composer will load all service providers in background.

### ISSUE THREAD

**Issue by Modelizer** [svenluijten/env-providers#2]
Hey, composer will load all service provider classes in background!, that means only instantiation is remaining. Can we do kind of trick where only those classes will be loaded by composer which are specified in `config`? This will help us in many ways. 😇

**Comment by svenluijten** [comment]
I would assume this is something to do with composer instead of this package specifically? Maybe a composer plugin would be the best course of action for that.

**Comment by Modelizer** [comment]
@svenluijten yes you are right. But if you able to manage to tell composer not to load these files from `config` then you have added advantage for you repo. Try to find if you get resource related to our discussion. 👍
