### ISSUE TITLE
Upgrade Illuminate Support

### ISSUE THREAD

**Issue by gogl92** [svenluijten/env-providers#34]
To make the package compatible with Laravel 9 Illuminate Support 9 needs to be added as well.

^8.0|^9.0

**Comment by sprklinginfo** [comment]
+1. Failed to install in Laravel 9. hope this issue can be resolved soon.

**Comment by svenluijten** [comment]
I don't know if you still need it, but I've just tagged [`v4.0.1`](https://github.com/svenluijten/env-providers/releases/tag/v4.0.1) which adds support for Laravel 9! `composer update sven/env-providers` should do the trick.
