### ISSUE TITLE
3.1.2 seems to have problems with package discovery

### ISSUE THREAD

**Issue by ebrigham1** [svenluijten/env-providers#9]
Hi @svenluijten I'm seeing a problem with package discovery in [v3.1.2](https://github.com/svenluijten/env-providers/tree/v3.1.2).

![env_providers_error](https://user-images.githubusercontent.com/7337543/58139529-10357700-7c09-11e9-8530-411eb1733c07.png)

composer.json seems to be looking for ["Sven\\EnvProviders\\EnvServiceProvider"](https://github.com/svenluijten/env-providers/blob/c792d8963af09f4b8afb79f5c1d7308b89f0327b/composer.json#L41) while the actual service provider seems to have been renamed to [ServiceProvider](https://github.com/svenluijten/env-providers/blob/c792d8963af09f4b8afb79f5c1d7308b89f0327b/src/ServiceProvider.php#L8) again.

I can put in a pull request to fix it, but I'm not sure which direction you want to take it so I figured I'd throw it in an issue and if you don't have time to work on it or just want to point me in a direction I should be able to put in a pull request for it.

Thanks,
-Ethan

**Comment by svenluijten** [comment]
Fixed in [v3.1.3](https://github.com/svenluijten/env-providers/releases/tag/v3.1.3), sorry it took so long for me to get around implementing this simple fix!
